[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.22"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "AHHFd8At9esnouazyFuEoKxZNyTKAfySR1vcNdxfBb3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
